# Generated by Django 5.2.6 on 2025-10-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indexapp', '0008_alter_cableoperadores_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=100, unique=True)),
                ('tipo_contrato', models.CharField(choices=[('tipo1', 'tipo1'), ('tipo2', 'tipo2'), ('tipo3', 'tipo3')], max_length=100)),
                ('estado_contrato', models.CharField(choices=[('Contratado', 'Contratado'), ('Finalizado', 'Finalizado'), ('En_Renovacion', 'En Renovacion'), ('Renovacion_firma_prst', 'En Renovacion - Firma PRST'), ('Renovacion_firma_air_e', 'En Renovacion - Firma AIR-E'), ('nuevo_firma_prst', 'Nuevo - Firma PRST'), ('nuevo_firma_air_e', 'Nuevo - Firma AIR-E'), ('En_Gestion', 'En Gestion'), ('Sin_usos', 'Sin Usos')], max_length=100)),
                ('duracion_anos', models.IntegerField()),
                ('inicio_vigencia', models.DateField()),
                ('fin_vigencia', models.DateField()),
                ('valor_contrato', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Garantia', models.CharField(max_length=100)),
                ('fecha_radicacion', models.DateField()),
                ('tipo_fecha_radicacion', models.CharField(max_length=100)),
                ('cableoperador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indexapp.cableoperadores')),
            ],
            options={
                'db_table': 'contratos',
            },
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contratos.contratos', verbose_name='Contrato Asociado')),
                ('tipo8', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de cables en postes de 8 metros')),
                ('tipo10', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de cables en postes de 10 metros')),
                ('tipo12', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de cables en postes de 12 metros')),
                ('tipo14', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de cables en postes de 14 metros')),
                ('tipo15', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de cables en postes de 15 metros')),
                ('tipo16', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de cables en postes de 16 metros')),
                ('tipo20', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de cables en postes de 20 metros')),
            ],
        ),
        migrations.CreateModel(
            name='Caja_empalme',
            fields=[
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contratos.contratos', verbose_name='Contrato Asociado')),
                ('tipo8', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de caja de empalme en postes de 8 metros')),
                ('tipo10', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de caja de empalme en postes de 10 metros')),
                ('tipo12', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de caja de empalme en postes de 12 metros')),
                ('tipo14', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de caja de empalme en postes de 14 metros')),
                ('tipo15', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de caja de empalme en postes de 15 metros')),
                ('tipo16', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de caja de empalme en postes de 16 metros')),
                ('tipo20', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de caja de empalme en postes de 20 metros')),
            ],
        ),
        migrations.CreateModel(
            name='Nap',
            fields=[
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contratos.contratos', verbose_name='Contrato Asociado')),
                ('tip8', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso nap en postes de 8 metros')),
                ('tip10', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso nap en postes de 10 metros')),
                ('tip12', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso nap en postes de 12 metros')),
                ('tip14', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso nap en postes de 14 metros')),
                ('tip15', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso nap en postes de 15 metros')),
                ('tip16', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso nap en postes de 16 metros')),
                ('tip20', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso nap en postes de 20 metros')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contratos.contratos', verbose_name='Contrato Asociado')),
                ('tipo8', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de reserva en postes de 8 metros')),
                ('tipo10', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de reserva en postes de 10 metros')),
                ('tipo12', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de reserva en postes de 12 metros')),
                ('tipo14', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de reserva en postes de 14 metros')),
                ('tipo15', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de reserva en postes de 15 metros')),
                ('tipo16', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de reserva en postes de 16 metros')),
                ('tipo20', models.PositiveIntegerField(default=0, verbose_name='Cantidad de uso de reserva en postes de 20 metros')),
            ],
        ),
    ]
