# Generated by Django 5.2.6 on 2025-10-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='fecha_radicacion',
            field=models.IntegerField(),
        ),
    ]
