# Generated by Django 5.2.6 on 2025-10-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_alter_contratos_fecha_radicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='tipo10',
            field=models.PositiveIntegerField(default=0, verbose_name='10 metros'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='tipo12',
            field=models.PositiveIntegerField(default=0, verbose_name='12 metros'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='tipo14',
            field=models.PositiveIntegerField(default=0, verbose_name='14 metros'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='tipo15',
            field=models.PositiveIntegerField(default=0, verbose_name='15 metros'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='tipo16',
            field=models.PositiveIntegerField(default=0, verbose_name='16 metros'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='tipo20',
            field=models.PositiveIntegerField(default=0, verbose_name='20 metros'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='tipo8',
            field=models.PositiveIntegerField(default=0, verbose_name='8 metros'),
        ),
        migrations.AlterField(
            model_name='caja_empalme',
            name='tipo10',
            field=models.PositiveIntegerField(default=0, verbose_name='10 metros'),
        ),
        migrations.AlterField(
            model_name='caja_empalme',
            name='tipo12',
            field=models.PositiveIntegerField(default=0, verbose_name='12 metros'),
        ),
        migrations.AlterField(
            model_name='caja_empalme',
            name='tipo14',
            field=models.PositiveIntegerField(default=0, verbose_name='14 metros'),
        ),
        migrations.AlterField(
            model_name='caja_empalme',
            name='tipo15',
            field=models.PositiveIntegerField(default=0, verbose_name='15 metros'),
        ),
        migrations.AlterField(
            model_name='caja_empalme',
            name='tipo16',
            field=models.PositiveIntegerField(default=0, verbose_name='16 metros'),
        ),
        migrations.AlterField(
            model_name='caja_empalme',
            name='tipo20',
            field=models.PositiveIntegerField(default=0, verbose_name='20 metros'),
        ),
        migrations.AlterField(
            model_name='caja_empalme',
            name='tipo8',
            field=models.PositiveIntegerField(default=0, verbose_name='8 metros'),
        ),
        migrations.AlterField(
            model_name='nap',
            name='tip10',
            field=models.PositiveIntegerField(default=0, verbose_name='10 metros'),
        ),
        migrations.AlterField(
            model_name='nap',
            name='tip12',
            field=models.PositiveIntegerField(default=0, verbose_name='12 metros'),
        ),
        migrations.AlterField(
            model_name='nap',
            name='tip14',
            field=models.PositiveIntegerField(default=0, verbose_name='14 metros'),
        ),
        migrations.AlterField(
            model_name='nap',
            name='tip15',
            field=models.PositiveIntegerField(default=0, verbose_name='15 metros'),
        ),
        migrations.AlterField(
            model_name='nap',
            name='tip16',
            field=models.PositiveIntegerField(default=0, verbose_name='16 metros'),
        ),
        migrations.AlterField(
            model_name='nap',
            name='tip20',
            field=models.PositiveIntegerField(default=0, verbose_name='20 metros'),
        ),
        migrations.AlterField(
            model_name='nap',
            name='tip8',
            field=models.PositiveIntegerField(default=0, verbose_name='8 metros'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo10',
            field=models.PositiveIntegerField(default=0, verbose_name='10 metros'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo12',
            field=models.PositiveIntegerField(default=0, verbose_name='12 metros'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo14',
            field=models.PositiveIntegerField(default=0, verbose_name='14 metros'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo15',
            field=models.PositiveIntegerField(default=0, verbose_name='15 metros'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo16',
            field=models.PositiveIntegerField(default=0, verbose_name='16 metros'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo20',
            field=models.PositiveIntegerField(default=0, verbose_name='20 metros'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo8',
            field=models.PositiveIntegerField(default=0, verbose_name='8 metros'),
        ),
        migrations.AlterModelTable(
            name='contratos',
            table='Contratos',
        ),
    ]
