# Generated by Django 5.2.6 on 2025-10-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_cable_tipo10_alter_cable_tipo12_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cable',
            table='Cables',
        ),
        migrations.AlterModelTable(
            name='caja_empalme',
            table='Cajas_empalme',
        ),
        migrations.AlterModelTable(
            name='nap',
            table='Naps',
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='Reservas',
        ),
    ]
