# Generated by Django 5.2.6 on 2025-10-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_cable_table_alter_caja_empalme_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='numero_contrato',
        ),
    ]
