# Generated by Django 5.2.6 on 2025-10-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_remove_contratos_numero_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='Garantia',
            field=models.CharField(choices=[('poliza_rce', 'Póliza de RCE'), ('poliza_cumplimiento', 'Póliza de Cumplimiento')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='estado_contrato',
            field=models.CharField(choices=[('Vigente', 'Vigente'), ('Vencido', 'Vencido')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='tipo_fecha_radicacion',
            field=models.CharField(choices=[('fija', 'Fija'), ('dinamica', 'Dinámica')], max_length=100),
        ),
    ]
