# Generated by Django 5.2.7 on 2025-10-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_alter_contratos_garantia_and_more'),
        ('indexapp', '0012_alter_cableoperadores_preliquidacion_num_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contratos',
            constraint=models.UniqueConstraint(condition=models.Q(('estado_contrato', 'Vigente')), fields=('estado_contrato',), name='unique_vigente_contrato'),
        ),
    ]
