# Generated by Django 5.2.6 on 2025-10-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_contratos_unique_vigente_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='Garantia',
        ),
        migrations.AddField(
            model_name='contratos',
            name='aseguradora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='expedicion_poliza_cumplimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='expedicion_poliza_rce',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fecha_preliquidacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fin_amparo_poliza_cumplimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fin_amparo_poliza_rce',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fin_vigencia_poliza_cumplimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fin_vigencia_poliza_rce',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='inicio_amparo_poliza_cumplimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='inicio_amparo_poliza_rce',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='inicio_vigencia_poliza_cumplimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='inicio_vigencia_poliza_rce',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='monto_asegurado_poliza_cumplimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='monto_asegurado_poliza_rce',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='numero_poliza_cumplimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='numero_poliza_rce',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='poliza_cumplimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='poliza_rce',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='tomador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='valor_asegurado_poliza_cumplimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='valor_asegurado_poliza_rce',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='valor_monto_asegurado_poliza_cumplimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='valor_monto_asegurado_poliza_rce',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='vigencia_amparo_poliza_cumplimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='vigencia_amparo_poliza_rce',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
