# Generated by Django 5.2.6 on 2025-10-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_remove_contratos_garantia_contratos_aseguradora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='poliza_cumplimiento',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='poliza_rce',
        ),
    ]
