# Generated by Django 5.2.6 on 2025-10-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_remove_contratos_poliza_cumplimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='monto_asegurado_poliza_cumplimiento',
            field=models.CharField(blank=True, choices=[('15%_valor_contrato', '15% Valor del Contrato'), ('20%_valor_contrato', '20% Valor del Contrato'), ('30%_valor_contrato', '30% Valor del Contrato'), ('20%_valor_base_constitucion_poliza', '20% Valor base de Constitución de Póliza'), ('30%_valor_base_constitucion_poliza', '30% Valor base de Constitución de Póliza')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='monto_asegurado_poliza_rce',
            field=models.CharField(blank=True, choices=[('no_inferior_100_SMLMV', 'No inferior a 100 SMLMV'), ('no_inferior_200_SMLMV', 'No inferior a 200 SMLMV'), ('no_inferior_300_SMLMV', 'No inferior a 300 SMLMV')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='valor_monto_asegurado_poliza_cumplimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='valor_monto_asegurado_poliza_rce',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='vigencia_amparo_poliza_cumplimiento',
            field=models.CharField(blank=True, choices=[('Igual_a_Duracion_de_Contrato_mas_12_Meses', 'Igual a Duración de Contrato + 12 Meses'), ('Igual_a_Duracion_de_Contrato_mas_6_Meses', 'Igual a Duración de Contrato + 6 Meses'), ('Igual_a_Duracion_de_Contrato_mas_4_Meses', 'Igual a Duración de Contrato + 4 Meses'), ('Igual_a_Duracion_de_Contrato_mas_2_Meses', 'Igual a Duración de Contrato + 2 Meses')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='vigencia_amparo_poliza_rce',
            field=models.CharField(blank=True, choices=[('Igual_a_Duracion_de_Contrato_mas_12_Meses', 'Igual a Duración de Contrato + 12 Meses'), ('Igual_a_Duracion_de_Contrato_mas_6_Meses', 'Igual a Duración de Contrato + 6 Meses'), ('Igual_a_Duracion_de_Contrato_mas_4_Meses', 'Igual a Duración de Contrato + 4 Meses'), ('Igual_a_Duracion_de_Contrato_mas_2_Meses', 'Igual a Duración de Contrato + 2 Meses')], max_length=100, null=True),
        ),
    ]
