# Generated by Django 5.2.6 on 2025-10-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_alter_contratos_monto_asegurado_poliza_cumplimiento_and_more'),
        ('indexapp', '0012_alter_cableoperadores_preliquidacion_num_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contratos',
            name='unique_vigente_contrato',
        ),
        migrations.AddConstraint(
            model_name='contratos',
            constraint=models.UniqueConstraint(condition=models.Q(('estado_contrato', 'Vencido')), fields=('estado_contrato',), name='unique_Vencido_contrato'),
        ),
    ]
