# Generated by Django 5.2.7 on 2025-10-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_remove_contratos_unique_vigente_contrato_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contratos',
            name='unique_Vencido_contrato',
        ),
        migrations.AlterField(
            model_name='contratos',
            name='aseguradora',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aseguradora'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='duracion_anos',
            field=models.IntegerField(default=0, verbose_name='Duración en años'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='estado_contrato',
            field=models.CharField(choices=[('Vigente', 'Vigente'), ('Vencido', 'Vencido')], max_length=100, verbose_name='Estado de Contrato'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='expedicion_poliza_cumplimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Expedición de Póliza'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='expedicion_poliza_rce',
            field=models.DateField(blank=True, null=True, verbose_name='Expedición de Póliza'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='fecha_preliquidacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Preliquidación'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='fecha_radicacion',
            field=models.IntegerField(verbose_name='Fecha de Radicación'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='fin_amparo_poliza_cumplimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de Amparo'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='fin_amparo_poliza_rce',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de Amparo'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='fin_vigencia_poliza_cumplimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de Vigencia'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='fin_vigencia_poliza_rce',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de Vigencia'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='inicio_amparo_poliza_cumplimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de Amparo'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='inicio_amparo_poliza_rce',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de Amparo'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='inicio_vigencia_poliza_cumplimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de Vigencia'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='inicio_vigencia_poliza_rce',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de Vigencia'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='monto_asegurado_poliza_cumplimiento',
            field=models.CharField(blank=True, choices=[('15%_valor_contrato', '15% Valor del Contrato'), ('20%_valor_contrato', '20% Valor del Contrato'), ('30%_valor_contrato', '30% Valor del Contrato'), ('20%_valor_base_constitucion_poliza', '20% Valor base de Constitución de Póliza'), ('30%_valor_base_constitucion_poliza', '30% Valor base de Constitución de Póliza')], max_length=100, null=True, verbose_name='Monto Asegurado'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='monto_asegurado_poliza_rce',
            field=models.CharField(blank=True, choices=[('no_inferior_100_SMLMV', 'No inferior a 100 SMLMV'), ('no_inferior_200_SMLMV', 'No inferior a 200 SMLMV'), ('no_inferior_300_SMLMV', 'No inferior a 300 SMLMV')], max_length=100, null=True, verbose_name='Monto Asegurado'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='numero_poliza_cumplimiento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Póliza'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='numero_poliza_rce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Póliza'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='tipo_contrato',
            field=models.CharField(choices=[('tipo1', 'tipo1'), ('tipo2', 'tipo2'), ('tipo3', 'tipo3')], max_length=100, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='tipo_fecha_radicacion',
            field=models.CharField(choices=[('fija', 'Fija'), ('dinamica', 'Dinámica')], max_length=100, verbose_name='Tipo de Fecha de Radicación'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='tomador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tomador'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='valor_asegurado_poliza_cumplimiento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor Asegurado'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='valor_asegurado_poliza_rce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor Asegurado'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='valor_contrato',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Valor del Contrato'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='valor_monto_asegurado_poliza_cumplimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor del Monto Asegurado'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='valor_monto_asegurado_poliza_rce',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor del Monto Asegurado'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='vigencia_amparo_poliza_cumplimiento',
            field=models.CharField(blank=True, choices=[('Igual_a_Duracion_de_Contrato_mas_12_Meses', 'Igual a Duración de Contrato + 12 Meses'), ('Igual_a_Duracion_de_Contrato_mas_6_Meses', 'Igual a Duración de Contrato + 6 Meses'), ('Igual_a_Duracion_de_Contrato_mas_4_Meses', 'Igual a Duración de Contrato + 4 Meses'), ('Igual_a_Duracion_de_Contrato_mas_2_Meses', 'Igual a Duración de Contrato + 2 Meses')], max_length=100, null=True, verbose_name='Vigencia de Amparo'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='vigencia_amparo_poliza_rce',
            field=models.CharField(blank=True, choices=[('Igual_a_Duracion_de_Contrato_mas_12_Meses', 'Igual a Duración de Contrato + 12 Meses'), ('Igual_a_Duracion_de_Contrato_mas_6_Meses', 'Igual a Duración de Contrato + 6 Meses'), ('Igual_a_Duracion_de_Contrato_mas_4_Meses', 'Igual a Duración de Contrato + 4 Meses'), ('Igual_a_Duracion_de_Contrato_mas_2_Meses', 'Igual a Duración de Contrato + 2 Meses')], max_length=100, null=True, verbose_name='Vigencia de Amparo'),
        ),
    ]
