# Generated by Django 5.2.6 on 2025-10-02 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ejecutiva responsable')),
                ('TipoIngreso', models.CharField(choices=[('Viabilidad', 'Viabilidad'), ('Desmonte', 'Desmonte'), ('Legalizacion', 'Legalizacion')], default='tipo1', max_length=100)),
                ('Formato02', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Formato solicitud Uso de infraestructura?')),
                ('Formato01', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Formato Caracterizacion de infraestructura?')),
                ('plano', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Tiene Plano de DWG?')),
                ('Georreferencia', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Tiene formato KMZ?')),
                ('DocSolicitante', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Tiene Documento del Solicitante?')),
                ('MatriculaSolicitante', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Tiene Matrícula del Solicitante?')),
                ('FotoMarquilla', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Tiene Fotografía de la Marquilla a instalar?')),
                ('tipo8', models.PositiveIntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 8')),
                ('tipo9', models.PositiveIntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 9')),
                ('tipo10', models.PositiveIntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 10')),
                ('tipo11', models.PositiveIntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 11')),
                ('tipo12', models.PositiveIntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 12')),
                ('tipo14', models.PositiveIntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 14')),
                ('tipo16', models.PositiveIntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 16')),
                ('departamento', models.CharField(choices=[('atlantico', 'Atlantico'), ('magdalena', 'Magdalena'), ('la_guajira', 'La Guajira')], max_length=20)),
                ('municipio', models.CharField(max_length=50, verbose_name='Municipio')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_radicacion', models.DateField(blank=True, null=True)),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(auto_now_add=True, null=True)),
                ('estado_ingreso', models.CharField(blank=True, choices=[('En_proceso', 'En proceso'), ('Cancelado', 'Cancelado')], default='En_proceso', max_length=100, null=True, verbose_name='Registro de estado del proyecto')),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
                ('cableoperador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.cableoperadores', verbose_name='Cableoperador')),
            ],
            options={
                'db_table': 'proyectos',
            },
        ),
    ]
