# Generated by Django 5.2.6 on 2025-10-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='responsable',
            field=models.CharField(max_length=100, verbose_name='Ejecutiva responsable'),
        ),
    ]
