# Generated by Django 5.2.6 on 2025-09-12 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indexapp', '0010_remove_proyectos_id_alter_proyectos_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion_proyectos',
            fields=[
                ('nombre_proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='indexapp.proyectos')),
                ('nombre_ingeniero', models.CharField(max_length=100)),
                ('persona_asignada', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
