# Generated by Django 5.2.6 on 2025-10-02 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion_proyectos',
            fields=[
                ('nombre_proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proyectos.proyectos')),
                ('nombre_ingeniero', models.CharField(max_length=100)),
                ('estado', models.CharField(default='En_progreso', max_length=100, verbose_name='Estado del Proyecto')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=1000, null=True)),
                ('persona_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asignacion_proyectos',
            },
        ),
    ]
