# Generated by Django 5.2.6 on 2025-09-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion', '0002_alter_asignacion_proyectos_persona_asignada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion_proyectos',
            name='estado',
            field=models.CharField(choices=[('1', 'En Progreso'), ('2', 'Completado')], default='1', max_length=100, verbose_name='Estado del Proyecto'),
        ),
    ]
