# Generated by Django 5.2.6 on 2025-09-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion', '0003_alter_asignacion_proyectos_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
