# Generated by Django 5.2.6 on 2025-09-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion', '0004_employee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asignacion_proyectos',
            table='asignacion_proyectos',
        ),
    ]
