# Generated by Django 5.2.6 on 2025-09-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion', '0005_alter_asignacion_proyectos_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterField(
            model_name='asignacion_proyectos',
            name='estado',
            field=models.CharField(choices=[('En_progreso', 'En Progreso'), ('Completado', 'Completado')], default='En_progreso', max_length=100, verbose_name='Estado del Proyecto'),
        ),
    ]
