# Generated by Django 5.2.6 on 2025-09-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion', '0006_delete_employee_alter_asignacion_proyectos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion_proyectos',
            name='estado',
            field=models.CharField(default='En_progreso', max_length=100, verbose_name='Estado del Proyecto'),
        ),
    ]
