# Generated by Django 5.2.6 on 2025-09-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignacion', '0007_alter_asignacion_proyectos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion_proyectos',
            name='fecha_asignacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
