# Generated by Django 5.2.6 on 2025-10-02 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cableoperadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_largo', models.CharField(blank=True, max_length=255, null=True)),
                ('NIT', models.CharField(blank=True, max_length=100, null=True)),
                ('RegistroTic', models.BigIntegerField(blank=True, null=True)),
                ('CodigoInterno', models.BigIntegerField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('Representante', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('ejecutiva', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Ejecutivas'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ejecutiva Asignada')),
            ],
            options={
                'db_table': 'cableoperadores',
            },
        ),
    ]
