# Generated by Django 5.2.6 on 2025-10-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cableoperadores',
            name='NIT',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='correo',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='ejecutiva',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='nombre_largo',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='telefono',
            field=models.BigIntegerField(default=0),
        ),
    ]
