# Generated by Django 5.2.6 on 2025-09-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0002_alter_proyectos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='DocSolicitante',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Tiene Documento del Solicitante?'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='Formato01',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Tiene Formato 01?'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='Formato02',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Tiene Formato 02?'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='FotoMarquilla',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Tiene Fotografía de la Marquilla a instalar?'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='Georreferencia',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Tiene Georreferencia?'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='MatriculaSolicitante',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Tiene Matrícula del Solicitante?'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='TipoIngreso',
            field=models.CharField(choices=[('tipo1', 'Viabilidad'), ('tipo2', 'Desmonte'), ('tipo3', 'Legalizacion')], default='tipo1', max_length=100),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='departamento',
            field=models.CharField(choices=[('atlantico', 'Atlantico'), ('magdalena', 'Magdalena'), ('la_guajira', 'La Guajira')], default='1', max_length=20, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='municipio',
            field=models.CharField(default='1', max_length=50, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='plano',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Tiene Plano?'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='responsable',
            field=models.CharField(default='', max_length=100),
        ),
    ]
