# Generated by Django 5.2.6 on 2025-10-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0002_alter_cableoperadores_nit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cableoperadores',
            name='correo',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='ejecutiva',
            field=models.CharField(max_length=100),
        ),
    ]
