# Generated by Django 5.2.6 on 2025-09-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0003_proyectos_docsolicitante_proyectos_formato01_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='fecha_radicacion',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='tipo10',
            field=models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 10'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='tipo11',
            field=models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 11'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='tipo12',
            field=models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 12'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='tipo14',
            field=models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 14'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='tipo16',
            field=models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 16'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='tipo8',
            field=models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 8'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='tipo9',
            field=models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 9'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='Formato01',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Formato Caracterizacion de infraestructura?'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='Formato02',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Formato solicitud Uso de infraestructura?'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='Georreferencia',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Tiene formato KMZ?'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='municipio',
            field=models.CharField(max_length=50, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='plano',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Tiene Plano de DWG?'),
        ),
    ]
