# Generated by Django 5.2.6 on 2025-10-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0003_alter_cableoperadores_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cableoperadores',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
