# Generated by Django 5.2.6 on 2025-10-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0004_alter_cableoperadores_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableoperadores',
            name='observaciones',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
