# Generated by Django 5.2.6 on 2025-09-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0004_proyectos_fecha_radicacion_proyectos_tipo10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='fecha_radicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo10',
            field=models.IntegerField(default='0000-00-00', verbose_name='Ingrese cantidad de Poste de Altura 10'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo11',
            field=models.IntegerField(default='0000-00-00', verbose_name='Ingrese cantidad de Poste de Altura 11'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo12',
            field=models.IntegerField(default='0000-00-00', verbose_name='Ingrese cantidad de Poste de Altura 12'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo14',
            field=models.IntegerField(default='0000-00-00', verbose_name='Ingrese cantidad de Poste de Altura 14'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo16',
            field=models.IntegerField(default='0000-00-00', verbose_name='Ingrese cantidad de Poste de Altura 16'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo8',
            field=models.IntegerField(default='0000-00-00', verbose_name='Ingrese cantidad de Poste de Altura 8'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo9',
            field=models.IntegerField(default='0000-00-00', verbose_name='Ingrese cantidad de Poste de Altura 9'),
        ),
    ]
