# Generated by Django 5.2.6 on 2025-10-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0005_cableoperadores_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cableoperadores',
            name='observaciones',
            field=models.TextField(max_length=1000),
        ),
    ]
