# Generated by Django 5.2.6 on 2025-09-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0005_alter_proyectos_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='tipo10',
            field=models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 10'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo11',
            field=models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 11'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo12',
            field=models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 12'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo14',
            field=models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 14'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo16',
            field=models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 16'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo8',
            field=models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 8'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo9',
            field=models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 9'),
        ),
    ]
