# Generated by Django 5.2.6 on 2025-09-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0006_alter_proyectos_tipo10_alter_proyectos_tipo11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='cableoperador',
            field=models.CharField(choices=[('1', 'CLARO'), ('2', 'TIGO'), ('3', 'MOVISTAR')], max_length=100, verbose_name='Cableoperador'),
        ),
    ]
