# Generated by Django 5.2.6 on 2025-10-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0007_cableoperadores_digito_verificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cableoperadores',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='preliquidacion_letra',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='preliquidacion_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='respuesta_preliquidacion',
            field=models.CharField(choices=[('Calendarios', 'Calendarios'), ('Habiles', 'Habiles')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='vencimiento_factura',
            field=models.IntegerField(),
        ),
    ]
