# Generated by Django 5.2.6 on 2025-09-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0007_alter_proyectos_cableoperador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='departamento',
            field=models.CharField(choices=[('atlantico', 'Atlantico'), ('magdalena', 'Magdalena'), ('la_guajira', 'La Guajira')], max_length=20),
        ),
    ]
