# Generated by Django 5.2.6 on 2025-09-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0008_alter_proyectos_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='TipoIngreso',
            field=models.CharField(choices=[('Viabilidad', 'Viabilidad'), ('Desmonte', 'Desmonte'), ('Legalizacion', 'Legalizacion')], default='tipo1', max_length=100),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='cableoperador',
            field=models.CharField(choices=[('CLARO', 'CLARO'), ('TIGO', 'TIGO'), ('MOVISTAR', 'MOVISTAR')], max_length=100, verbose_name='Cableoperador'),
        ),
    ]
