# Generated by Django 5.2.6 on 2025-09-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0009_alter_proyectos_tipoingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='id',
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
