# Generated by Django 5.2.6 on 2025-10-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0010_alter_cableoperadores_ejecutiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cableoperadores',
            name='CodigoInterno',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Codigo Interno'),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='Digito_verificacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Digito de verificación'),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='RegistroTic',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Registro TIC'),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='correo',
            field=models.EmailField(max_length=100, verbose_name='Correo (Obligatorio)'),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='estado',
            field=models.CharField(choices=[('Contratado', 'Contratado'), ('Finalizado', 'Finalizado'), ('En_Renovacion', 'En Renovacion'), ('Renovacion_firma_prst', 'En Renovacion - Firma PRST'), ('Renovacion_firma_air_e', 'En Renovacion - Firma AIR-E'), ('nuevo_firma_prst', 'Nuevo - Firma PRST'), ('nuevo_firma_air_e', 'Nuevo - Firma AIR-E'), ('En_Gestion', 'En Gestion'), ('Sin_usos', 'Sin Usos')], max_length=100, verbose_name='Estado (Obligatorio)'),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre (Obligatorio)'),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='observaciones',
            field=models.TextField(max_length=1000, verbose_name='Observaciones (Obligatorio)'),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='preliquidacion_letra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Preliquidacion Letra'),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='preliquidacion_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Preliquidacion Numero'),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='respuesta_preliquidacion',
            field=models.CharField(blank=True, choices=[('Calendarios', 'Calendarios'), ('Habiles', 'Habiles')], max_length=100, null=True, verbose_name='Respuesta Preliquidacion'),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='telefono',
            field=models.BigIntegerField(verbose_name='Teléfono (Obligatorio)'),
        ),
    ]
