# Generated by Django 5.2.6 on 2025-09-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0011_alter_proyectos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='fecha_revision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='responsable',
            field=models.CharField(max_length=100),
        ),
    ]
