# Generated by Django 5.2.6 on 2025-10-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0011_alter_cableoperadores_codigointerno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cableoperadores',
            name='preliquidacion_num',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Preliquidacion Numero'),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='vencimiento_factura',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
