# Generated by Django 5.2.6 on 2025-09-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0012_proyectos_fecha_entrega_proyectos_fecha_revision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cableoperadores',
            name='nit',
        ),
        migrations.AddField(
            model_name='cableoperadores',
            name='nombre_largo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
