# Generated by Django 5.2.6 on 2025-09-17 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0013_remove_cableoperadores_nit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='cableoperador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.cableoperadores', verbose_name='Cableoperador'),
        ),
    ]
