# Generated by Django 5.2.6 on 2025-09-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0015_alter_proyectos_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cableoperadores',
            table='cableoperadores',
        ),
    ]
