# Generated by Django 5.2.6 on 2025-09-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0017_proyectos_estado_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='estado_ingreso',
            field=models.CharField(blank=True, choices=[('En_proceso', 'En proceso'), ('Cancelado', 'Cancelado')], default='En_proceso', max_length=100, null=True, verbose_name='Registro de estado del proyecto'),
        ),
    ]
