# Generated by Django 5.2.6 on 2025-09-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0018_alter_proyectos_estado_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='fecha_entrega',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
