# Generated by Django 5.2.6 on 2025-09-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0019_alter_proyectos_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableoperadores',
            name='NIT',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cableoperadores',
            name='direccion',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo10',
            field=models.PositiveIntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 10'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo11',
            field=models.PositiveIntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 11'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo12',
            field=models.PositiveIntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 12'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo14',
            field=models.PositiveIntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 14'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo16',
            field=models.PositiveIntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 16'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo8',
            field=models.PositiveIntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 8'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='tipo9',
            field=models.PositiveIntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 9'),
        ),
    ]
