# Generated by Django 5.2.6 on 2025-09-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0020_cableoperadores_nit_cableoperadores_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableoperadores',
            name='CodigoInterno',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cableoperadores',
            name='RegistroTic',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cableoperadores',
            name='Representante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cableoperadores',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cableoperadores',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cableoperadores',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cableoperadores',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='NIT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cableoperadores',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
