# Generated by Django 5.2.6 on 2025-09-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0021_cableoperadores_codigointerno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cableoperadores',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
