# Generated by Django 5.2.6 on 2025-09-30 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0022_alter_cableoperadores_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cableoperadores',
            name='ejecutiva',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Ejecutivas'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ejecutiva Asignada'),
        ),
    ]
