# Generated by Django 5.2.6 on 2025-10-02 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Responsable', models.CharField(max_length=100, verbose_name='Responsable')),
                ('Clasificacion', models.CharField(choices=[('tipo1', 'tipo1'), ('tipo2', 'tipo2'), ('tipo3', 'tipo3')], max_length=50, verbose_name='Clasificación')),
                ('Mes_uso', models.DateField(verbose_name='Mes de Uso')),
                ('Fecha_fact', models.DateField(verbose_name='Fecha de Facturación')),
                ('Num_fact', models.CharField(max_length=50, unique=True, verbose_name='Número de Factura')),
                ('Valor_iva', models.FloatField(max_length=50, verbose_name='Valor IVA')),
                ('Valor_iva_millones', models.FloatField(verbose_name='Valor en millones')),
                ('Fecha_venc', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('Periodo_venc', models.DateField(verbose_name='Periodo de Vencimiento')),
                ('Factura_aceptada', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=50, verbose_name='Factura aceptada')),
                ('Factura_vencida', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=50, verbose_name='Vencida')),
                ('Factura_CRC', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=50, verbose_name='Facturado CRC')),
                ('Valor_pagado', models.FloatField(verbose_name='Valor Pagado')),
                ('Fecha_pago', models.DateField(verbose_name='Fecha pago')),
                ('Periodo_pago', models.DateField(verbose_name='Periodo pago')),
                ('Fecha_aplicacion', models.DateField(max_length=50, verbose_name='Fecha de aplicacion')),
                ('Fecha_confirmacion', models.DateField(blank=True, null=True, verbose_name='Fecha de confirmacion')),
                ('Valor_deuda', models.FloatField(verbose_name='Valor deuda')),
                ('Pagado', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=50, verbose_name='Pagado?')),
                ('Observciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('Interes_iva', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=50, verbose_name='Interes IVA')),
                ('Indicador_recaudo', models.DateField(verbose_name='Inducador de recaudo')),
                ('Acuerdo_pago', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=50, verbose_name='Acuerdo de pago?')),
                ('Fecha_acuerdo_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de acuerdo de pago')),
                ('Fecha_pago_AP', models.DateField(blank=True, null=True, verbose_name='Fecha de pago acuerdo de pago')),
                ('Nombre_prst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.cableoperadores', verbose_name='Nombre del Prestador')),
            ],
            options={
                'db_table': 'Facturacion',
            },
        ),
    ]
