# Generated by Django 5.2.6 on 2025-09-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='Fecha_acuerdoP',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de acuerdo de pago'),
        ),
        migrations.AlterField(
            model_name='facturacion',
            name='Fecha_pago_AP',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago acuerdo de pago'),
        ),
    ]
