# Generated by Django 5.2.6 on 2025-09-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_alter_facturacion_fecha_acuerdop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='Num_fact',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de Factura'),
        ),
    ]
