# Generated by Django 5.2.6 on 2025-09-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_facturacion_num_fact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturacion',
            old_name='Fecha_acuerdoP',
            new_name='Fecha_acuerdo_pago',
        ),
    ]
